name: Simple Machines Forum
identifier: org.simplemachines.smf
version: 3.0
author:
    name: Simple Machines
    email: norv@simplemachines.org
    website: http://simplemachines.org
namespaces:
    php: smCore\modules\smf
    lang: smf
    template: smf

routes:
    boardindex:
        match: forum
        controller: BoardIndex
        method: main
events:
    smCore.post_router:
        callback: [\smCore\modules\smf\helpers\Loader.php, postRouter]
        enabled: true
    smCore.core_config_loaded:
        callback: [\smCore\modules\smf\helpers\Loader.php, coreConfigLoaded]
        enabled: true
    smCore.core_user_groups_loaded:
        callback: [\smCore\modules\smf\helpers\ForumMember.php, coreGroupsLoaded]
        enabled: true